[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja; sys_platform != 'win32'",
    "cmake>=3.12",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Run the package tests on every wheel using `pytest`
test-command = "pytest {package}/tests"

# will install pytest and other packages in the `test` extra
test-extras = ["test"]
